# Конфигурация приложения
app:
  name: "mqtt-http-bridge"
  version: "0.0.1"

# Настройки логгера
log:
  level: "debug" # debug, info, warn, error

# Настройки MQTT клиента(ТЕСТОВЫЕ)
mqtt:
  broker: "192.168.1.2:1883"
  client_id: "zigbee-server"
  new_divice_topic: "tele/+/+/SENSOR"
  qos: 1
  clean_session: true
  keep_alive: 60
  connect_timeout: 30

# Настройки http сервера (ТЕСТОВЫЕ)
http:
  host: "localhost"
  port: 8080


# Настройки базы данных (ТЕСТОВЫЕ)
database:
  host: "localhost"
  port: 5432
  name: "lotdb"
  user: "admin"
  password: "admin"

